#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : deprecated-colorama
Version  : 0.3.9
Release  : 55
URL      : https://pypi.debian.net/colorama/colorama-0.3.9.tar.gz
Source0  : https://pypi.debian.net/colorama/colorama-0.3.9.tar.gz
Summary  : Cross-platform colored terminal text.
Group    : Development/Tools
License  : BSD-3-Clause
Requires: deprecated-colorama-license = %{version}-%{release}
Requires: deprecated-colorama-python = %{version}-%{release}
BuildRequires : buildreq-distutils
BuildRequires : buildreq-distutils3

%description
.. image:: https://img.shields.io/pypi/v/colorama.svg
:target: https://pypi.python.org/pypi/colorama/
:alt: Latest Version

%package legacypython
Summary: legacypython components for the deprecated-colorama package.
Group: Default
Requires: python-core

%description legacypython
legacypython components for the deprecated-colorama package.


%package license
Summary: license components for the deprecated-colorama package.
Group: Default

%description license
license components for the deprecated-colorama package.


%package python
Summary: python components for the deprecated-colorama package.
Group: Default

%description python
python components for the deprecated-colorama package.


%prep
%setup -q -n colorama-0.3.9

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C
export SOURCE_DATE_EPOCH=1554309058
export MAKEFLAGS=%{?_smp_mflags}
python2 setup.py build -b py2

%install
export MAKEFLAGS=%{?_smp_mflags}
rm -rf %{buildroot}
mkdir -p %{buildroot}/usr/share/package-licenses/deprecated-colorama
cp LICENSE.txt %{buildroot}/usr/share/package-licenses/deprecated-colorama/LICENSE.txt
python2 -tt setup.py build -b py2 install --root=%{buildroot}

%files
%defattr(-,root,root,-)

%files legacypython
%defattr(-,root,root,-)
/usr/lib/python2*/*

%files license
%defattr(0644,root,root,0755)
/usr/share/package-licenses/deprecated-colorama/LICENSE.txt

%files python
%defattr(-,root,root,-)
